version: "3.2"

# FHIR Appliance Quickstart for Windows containers

services:
  # https://hub.docker.com/r/microsoft/mssql-server-windows-express/
  fhir-appliance-db:
    image: microsoft/mssql-server-windows-express
    container_name: fhir-appliance-db
    hostname: localhost
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa55w0rd1! # Change as required (changes here need to be reflected in line 44 of .env)
      - ATTACH_DBS=[{"dbName":"fhirstore","dbFiles":["C:\\Data\\fhirstore.mdf","C:\\Data\\fhirstore_log.ldf"]}]
    ports:
      - 1433:1433
    volumes:
      - C:\\repos\\docker_windows\\fhir-appliance\quickstart\windows\data\:C:\Data

  fhir-appliance:
    image: synaneticsltd/synfhir-store:windows-2019-beta-v3.1.0
    restart: always
    container_name: fhir-appliance
    environment:
      # Settings required by moleculer (not configurable)
      - METRICSENABLE=false
      - NAMESPACE=fhir-appliance
      - NODE_ENV=development
      - SERVICEDIR=services
      - SERVICES=**/*.service.js
    env_file:
      - .env
    ports:
      # Public endpoint (https)
      # Map 443 of the host to 443 in the container if using SSL
      - 443:443
      # Integration endpoint (http)
      - 8300:8300
    depends_on:
      - fhir-appliance-db
    volumes:
      # Copy .pem formatted SSL certificates: certificate, private key, passphrase (optional) and, if using mutal tls, root CA certificate to ssl if securing the endpoint
      - ..\shared\ssl:C:\app\ssl
      # If using public key based JSON web token verification then copy public key of CA to keys folder (see environment file for information)
      - ..\shared\keys:C:\app\keys
    networks:
      - default