version: "3.2"

# FHIR Appliance Quickstart with Linux containers

# Change the passwords as required - you will need to reflect password changes made to the fhir-appliance-db container in the database connection string (line 44) of the .env file

services:
  fhir-appliance-db:
    image: postgres
    container_name: fhir-appliance-db
    restart: always
    environment:
      - POSTGRES_DB=fhirstore
      - POSTGRES_USER=iamonfhir
      - POSTGRES_PASSWORD=Pa55w0rd1! # you will need to reflect password changes made here in the database connection string (line 44) of the .env file
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

  # The following a free web based client for postgres.
  # Once started, you can access the client at http://localhost:54321
  # Login details are provided but feel free to change if required.

  fhir-appliance-db-client:
    image: dpage/pgadmin4
    restart: always
    container_name: fhir-appliance-db-client
    environment:
      - PGADMIN_DEFAULT_EMAIL=support@myorg.org
      - PGADMIN_DEFAULT_PASSWORD=Pa55w0rd1!
    ports:
      - 54321:80
    depends_on:
      - fhir-appliance-db
    networks:
      - default

  fhir-appliance:
    image: synaneticsltd/synfhir-store:linux-beta-v3.1.0
    restart: always
    container_name: fhir-appliance
    environment:
      # Settings required by moleculer (not configurable)
      - METRICSENABLE=false
      - NAMESPACE=fhir-appliance
      - NODE_ENV=development
      - SERVICEDIR=services
      - SERVICES=**/*.service.js
    env_file:
      - .env
    ports:
      # Public endpoint (https)
      # Map 443 of the host to 443 in the container if using SSL
      - 443:443
      # Integration endpoint (http)
      - 8300:8300
    depends_on:
      - fhir-appliance-db
    volumes:
      # Copy .pem formatted SSL certificates: certificate, private key, passphrase (optional) and, if using mutal tls, root CA certificate to ./ssl if securing the endpoint
      - ../shared/ssl:/app/ssl
      # If using public key based JSON web token verification then copy public key of CA to ./keys folder (see environment file for information)
      - ../shared/keys:/app/keys
    networks:
      - default

volumes:
  pgdata:
